name: BetterPlayerLeads
version: '${project.version}'
main: me.swipez.betterplayerleads.BetterPlayerLeads
api-version: 1.18
authors: [ notnotnotswipez ]
commands:
  ropelength:
    usage: /ropelength <player> <length>
permissions:
    betterleads.all:
      children:
        betterleads.lead:
          description: Allows players to lead other players.
          default: true
        betterleads.command:
          description: Allows players to use the rope length command.
          default: true
